language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_script:
  - phpize
  - ./configure
  - make

script:
  - export NO_INTERACTION=1
  - export REPORT_EXIT_STATUS=1
  - export TEST_PHP_EXECUTABLE=`which php`
  - php run-tests.php -d extension=zopfli.so -d extension_dir=modules -n ./tests/
  - for i in `find tests -name "*.out" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

